fix: service wrapper was removed as it has been rolled into the Devic…
edgexfoundry/device-rfid-llrp-go pull request #104
Opened 2022-08-02 20:50 UTC by marcpfuller

…eServiceSDK interface

Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-rfid-llrp-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
 N/A

## Testing Instructions
make test

## New Dependency Instructions (If applicable)

2022-08-09 23:00 UTC, lenny-intel requested changes
Nice job with the mocks!

2022-08-10 21:07 UTC, marcpfuller commented on internal/driver/discover_test.go
> +	// svc.clearDevices()
I left them un commented,  as I wasnt sure if the way I did the mocks would be sufficient

2022-08-10 21:10 UTC, marcpfuller commented on internal/driver/driver.go
> +	d.svc = service.RunningService()
I think either works. I wasnt sure  which should be used, so I used this instead

2022-08-10 21:10 UTC, marcpfuller commented on internal/driver/discover_test.go
> +	// svc.clearDevices()
I have removed the comment

2022-08-10 21:11 UTC, marcpfuller commented on internal/driver/discover_test.go
> +	// svc.AddDiscoveredDevices(discovered)
I have removed the comment

2022-08-10 21:11 UTC, marcpfuller commented on internal/driver/discover_test.go
> +	// svc.clearDevices()
I have removed the comment

2022-08-10 21:51 UTC, lenny-intel approved these changes
LGTM

2022-08-10 21:56 UTC, lenny-intel approved these changes

2022-08-10 22:09 UTC, merged